version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis_server:6379

  redis:
    image: redis:7.0-alpine
    container_name: redis_server
    ports:
      - "6379:6379"  # Redis 기본 포트 매핑